# Generated by Django 2.0.13 on 2020-01-14 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ma400In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='남자', max_length=5, verbose_name='성별')),
                ('start_year', models.IntegerField(default=2010, verbose_name='납입년')),
                ('start_month', models.IntegerField(default=10, verbose_name='납입월')),
                ('premium', models.IntegerField(default=1000000, verbose_name='월보험료')),
                ('paying_period', models.IntegerField(default=10, verbose_name='납입기간')),
                ('present_age', models.IntegerField(default=45, verbose_name='현재연령')),
                ('pention_start_age', models.IntegerField(default=65, verbose_name='연금개시연령')),
                ('earning_rate', models.DecimalField(decimal_places=1, default=7.0, max_digits=5, verbose_name='변액수익률')),
                ('pention_start_rate', models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='연금개시시이율')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ma400Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='남자', max_length=5, verbose_name='성별')),
                ('start_year', models.IntegerField(default=2010, verbose_name='납입년')),
                ('start_month', models.IntegerField(default=1, verbose_name='납입월')),
                ('premium', models.IntegerField(default=1000000, verbose_name='월보험료')),
                ('paying_period', models.IntegerField(default=10, verbose_name='납입기간')),
                ('present_age', models.IntegerField(default=45, verbose_name='현재연령')),
                ('pention_start_age', models.IntegerField(default=65, verbose_name='연금개시연령')),
                ('earning_rate', models.DecimalField(decimal_places=2, default=7, max_digits=5, verbose_name='변액수익률')),
                ('public_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='공시이율이자')),
                ('pention_start_rate', models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='연금개시시이율')),
                ('wholelife_annuity_10', models.IntegerField()),
                ('wholelife_annuity_20', models.IntegerField()),
                ('wholelife_annuity_80', models.IntegerField()),
                ('annuity_certain_10', models.IntegerField()),
                ('annuity_certain_15', models.IntegerField()),
                ('annuity_certain_20', models.IntegerField()),
                ('annuity_inherit', models.IntegerField()),
                ('lump_sum_of_death', models.IntegerField()),
                ('total_premium', models.IntegerField()),
                ('reserve_money', models.IntegerField()),
                ('life_table', models.CharField(default='8회', max_length=5, verbose_name='경험생명표')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ma600In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='남자', max_length=5, verbose_name='성별')),
                ('start_year', models.IntegerField(default=2010, verbose_name='납입년')),
                ('start_month', models.IntegerField(default=10, verbose_name='납입월')),
                ('premium', models.IntegerField(default=1000000, verbose_name='월보험료')),
                ('paying_period', models.IntegerField(default=10, verbose_name='납입기간')),
                ('present_age', models.IntegerField(default=45, verbose_name='현재연령')),
                ('pention_start_age', models.IntegerField(default=65, verbose_name='연금개시연령')),
                ('public_rate', models.DecimalField(decimal_places=1, default=2.5, max_digits=5, verbose_name='공시이율이자')),
                ('pention_start_rate', models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='연금개시시이율')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ma600Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='남자', max_length=5, verbose_name='성별')),
                ('start_year', models.IntegerField(default=2010, verbose_name='납입년')),
                ('start_month', models.IntegerField(default=1, verbose_name='납입월')),
                ('premium', models.IntegerField(default=1000000, verbose_name='월보험료')),
                ('paying_period', models.IntegerField(default=10, verbose_name='납입기간')),
                ('present_age', models.IntegerField(default=45, verbose_name='현재연령')),
                ('pention_start_age', models.IntegerField(default=65, verbose_name='연금개시연령')),
                ('earning_rate', models.DecimalField(decimal_places=2, default=7, max_digits=5, verbose_name='변액수익률')),
                ('public_rate', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='공시이율이자')),
                ('pention_start_rate', models.DecimalField(decimal_places=1, default=2.0, max_digits=3, verbose_name='연금개시시이율')),
                ('wholelife_annuity_10', models.IntegerField()),
                ('wholelife_annuity_20', models.IntegerField()),
                ('wholelife_annuity_80', models.IntegerField()),
                ('annuity_certain_10', models.IntegerField()),
                ('annuity_certain_15', models.IntegerField()),
                ('annuity_certain_20', models.IntegerField()),
                ('annuity_inherit', models.IntegerField()),
                ('lump_sum_of_death', models.IntegerField()),
                ('total_premium', models.IntegerField()),
                ('reserve_money', models.IntegerField()),
                ('life_table', models.CharField(default='8회', max_length=5, verbose_name='경험생명표')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
