# Generated by Django 2.0.13 on 2020-01-14 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pentionsto', '0002_ma400out01'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ma600Out01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_month', models.IntegerField(default=100, verbose_name='경과월')),
                ('age', models.IntegerField(default=45, verbose_name='연령')),
                ('path_year', models.IntegerField(default=10, verbose_name='경과년')),
                ('total_premium', models.IntegerField(default=100000000, verbose_name='총납입현황')),
                ('payment', models.IntegerField(default=130000000, verbose_name='계약자적립금')),
                ('return_money', models.IntegerField(default=130000000, verbose_name='해지환급금')),
                ('year', models.CharField(default='1년', max_length=25, verbose_name='경과년월')),
                ('return_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='환급률')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ma400out01',
            name='expect_rate',
        ),
    ]
