# Generated by Django 2.0.13 on 2019-10-25 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aa01Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(default='1996-01-10', verbose_name='생년월일')),
                ('end_date', models.DateField(default='2019-08-10', verbose_name='종료일')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aa02Insuage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insu_age', models.IntegerField(default=100, verbose_name='경과월')),
                ('birth_date', models.DateField(default='1996-01-10', verbose_name='생년월일')),
                ('end_date', models.DateField(default='2019-08-10', verbose_name='종료일')),
            ],
        ),
    ]
