# Generated by Django 2.0.13 on 2019-11-01 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aa01Totalcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField(default=100, verbose_name='총 편입비율')),
                ('amount', models.IntegerField(default=5, verbose_name='펀드개수')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aa07Presentpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_premium', models.IntegerField(default=100000000, verbose_name='총납입현황')),
                ('payment', models.IntegerField(default=130000000, verbose_name='계약자적립금')),
                ('return_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='수익률')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aa08Expectrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expect_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='예상수익률')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aa12Pentionout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whole_10', models.IntegerField(default=130000000, verbose_name='상속연금10년보증')),
                ('whole_20', models.IntegerField(default=130000000, verbose_name='상속연금20년보증')),
                ('whole_80', models.IntegerField(default=130000000, verbose_name='상속연금80세보증')),
                ('set_10', models.IntegerField(default=130000000, verbose_name='10년확정')),
                ('set_15', models.IntegerField(default=130000000, verbose_name='15년확정')),
                ('set_20', models.IntegerField(default=130000000, verbose_name='20년확정')),
                ('inherit_month', models.IntegerField(default=130000000, verbose_name='상속연금')),
                ('inherit_lumpsum', models.IntegerField(default=130000000, verbose_name='상속일시금')),
                ('total_whole_10', models.IntegerField(default=130000000, verbose_name='총상속연금10년보증')),
                ('total_whole_20', models.IntegerField(default=130000000, verbose_name='총상속연금20년보증')),
                ('total_whole_80', models.IntegerField(default=130000000, verbose_name='총상속연금80세보증')),
                ('total_set_10', models.IntegerField(default=130000000, verbose_name='총10년확정')),
                ('total_set_15', models.IntegerField(default=130000000, verbose_name='총15년확정')),
                ('total_set_20', models.IntegerField(default=130000000, verbose_name='총20년확정')),
                ('total_inherit_month', models.IntegerField(default=130000000, verbose_name='총상속연금')),
                ('total_premium', models.IntegerField(default=130000000, verbose_name='총납입보험료')),
                ('pention_money', models.IntegerField(default=130000000, verbose_name='연금개시재원')),
                ('return_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='환급률')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ab02fundprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_code', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(default='2010-10-02', null=True, verbose_name='기준일자')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='기준가')),
                ('count', models.IntegerField(null=True, verbose_name='편입비율')),
            ],
        ),
        migrations.CreateModel(
            name='Metfund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(db_index=True, max_length=200)),
                ('fund_code', models.CharField(max_length=200, null=True)),
                ('create_date', models.DateField(default='2010-10-02', null=True, verbose_name='설정일')),
                ('fund_type01', models.CharField(default='국내투자', max_length=30, null=True, verbose_name='펀드유형')),
                ('fund_type02', models.CharField(default='주식형', max_length=30, null=True, verbose_name='펀드유형')),
                ('stock_percent', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True, verbose_name='편입비율')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
