# Generated by Django 2.0.13 on 2019-11-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders07', '0003_ab03fund01price_ab03fund02price_ab03fund03price_ab03fund04price_ab03fund05price_ab03fund06price_ab03'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ab03fund01price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab03fund02price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab03fund03price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab03fund04price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab03fund05price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab03fund06price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab03fund07price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab03fund08price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab03fund09price',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ab03fund01price',
        ),
        migrations.DeleteModel(
            name='Ab03fund02price',
        ),
        migrations.DeleteModel(
            name='Ab03fund03price',
        ),
        migrations.DeleteModel(
            name='Ab03fund04price',
        ),
        migrations.DeleteModel(
            name='Ab03fund05price',
        ),
        migrations.DeleteModel(
            name='Ab03fund06price',
        ),
        migrations.DeleteModel(
            name='Ab03fund07price',
        ),
        migrations.DeleteModel(
            name='Ab03fund08price',
        ),
        migrations.DeleteModel(
            name='Ab03fund09price',
        ),
    ]
