# Generated by Django 2.0.13 on 2020-01-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders07', '0006_ab02fund01price_ab02fund02price_ab02fund03price_ab02fund04price_ab02fund05price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ab02fund01price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab02fund02price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab02fund03price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab02fund04price',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ab02fund05price',
            name='user',
        ),
        migrations.DeleteModel(
            name='Ab02fund01price',
        ),
        migrations.DeleteModel(
            name='Ab02fund02price',
        ),
        migrations.DeleteModel(
            name='Ab02fund03price',
        ),
        migrations.DeleteModel(
            name='Ab02fund04price',
        ),
        migrations.DeleteModel(
            name='Ab02fund05price',
        ),
    ]
