# Generated by Django 2.0.13 on 2020-01-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders07', '0007_auto_20200108_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac06metrate',
            name='fund_no',
            field=models.IntegerField(default=4, verbose_name='펀드no'),
        ),
    ]
