# Generated by Django 2.0.13 on 2019-10-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_auth',
            field=models.IntegerField(default=1, verbose_name='회원권한'),
        ),
    ]
