# Generated by Django 2.2 on 2019-04-09 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ma000insu_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insu_name', models.TextField(default='변액연금보험 동행', max_length=100, verbose_name='보험명')),
                ('company', models.CharField(default='삼성', max_length=30, verbose_name='보험사')),
                ('sell_start', models.DateField(default='2010-10-02', verbose_name='판매개시')),
                ('sell_end', models.DateField(default='2099-12-31', verbose_name='판매종료')),
                ('fund_count', models.IntegerField(default=10, verbose_name='펀드수')),
                ('sign_charge7', models.DecimalField(decimal_places=2, default=6.06, max_digits=5, verbose_name='계약체결비용(7년 이내)')),
                ('sign_charge810', models.DecimalField(decimal_places=2, default=6.06, max_digits=5, verbose_name='계약체결비용(8년~10년)')),
                ('management_charge7', models.DecimalField(decimal_places=2, default=3.23, max_digits=7, verbose_name='관리/유지비용(7년 이내)')),
                ('management_charge810', models.DecimalField(decimal_places=2, default=5.0, max_digits=7, verbose_name='관리/유지비용(7년~10년)')),
                ('management_charge11', models.DecimalField(decimal_places=1, default=1.5, max_digits=5, verbose_name='관리/유지비용(10년 초과)')),
                ('sign_charge1', models.DecimalField(decimal_places=2, default=6.06, max_digits=5, verbose_name='계약체결비용(7년 이내)')),
                ('management_charge1', models.DecimalField(decimal_places=2, default=3.23, max_digits=7, verbose_name='관리/유지비용(7년 이내)')),
                ('management_charge2', models.DecimalField(decimal_places=2, default=5.0, max_digits=7, verbose_name='관리/유지비용(7년~10년)')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='업데이트일자')),
                ('gender', models.CharField(default='남자', max_length=5, verbose_name='성별')),
                ('entry_date', models.DateField(default='2010-01-01', verbose_name='가입일')),
                ('premium', models.IntegerField(default=1000000, verbose_name='월보험료')),
                ('paying_period', models.IntegerField(default=10, verbose_name='납입기간')),
                ('present_age', models.IntegerField(default=45, verbose_name='현재연령')),
                ('transfer_date', models.IntegerField(default=10, verbose_name='이체일')),
                ('entry_method', models.CharField(default='적립', max_length=30, verbose_name='납입방법')),
                ('risk_premium', models.IntegerField(default=1000, verbose_name='위험보험료')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ma001fund_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insu_name', models.TextField(default='변액연금보험 동행', max_length=100, verbose_name='보험명')),
                ('fund_code', models.CharField(default='1234', max_length=30, verbose_name='펀드코드')),
                ('company', models.CharField(default='미래에셋', max_length=30, verbose_name='운용사')),
                ('create_date', models.DateField(default='2010-10-02', verbose_name='설정일')),
                ('stock_percent', models.IntegerField(default=10, verbose_name='주식비중')),
                ('fund_name', models.CharField(default='주식형', max_length=30, verbose_name='펀드명')),
                ('fund_type01', models.CharField(default='주식형', max_length=30, verbose_name='펀드유형')),
                ('fund_type02', models.CharField(default='주식형', max_length=30, verbose_name='펀드유형')),
                ('manage_company', models.CharField(default='삼성자산운용', max_length=30, verbose_name='운용사')),
                ('input_percent', models.IntegerField(default=10, verbose_name='투입비율')),
                ('insu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vund.Ma000insu_list')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
