# Generated by Django 2.2 on 2019-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma000insu_list',
            name='insu_name02',
            field=models.TextField(default='변액연금보험 동행', max_length=100, verbose_name='보험명'),
        ),
    ]
