# Generated by Django 2.2 on 2019-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0002_ma000insu_list_insu_name02'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma001fund_list',
            name='insu_name02',
            field=models.TextField(default='변액연금보험 동행', max_length=100, verbose_name='보험명'),
        ),
    ]
