# Generated by Django 2.2 on 2019-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0003_ma001fund_list_insu_name02'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ma001fund_list',
            name='insu_name02',
        ),
        migrations.AddField(
            model_name='ma001fund_list',
            name='fund_name02',
            field=models.CharField(default='주식형', max_length=30, verbose_name='펀드명'),
        ),
    ]
