# Generated by Django 2.2 on 2019-04-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0004_auto_20190409_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='fund_count',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='insu_name02',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='management_charge1',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='management_charge11',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='management_charge2',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='management_charge7',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='management_charge810',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='sell_end',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='sell_start',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='sign_charge1',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='sign_charge7',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='sign_charge810',
        ),
        migrations.DeleteModel(
            name='Ma001fund_list',
        ),
    ]
