# Generated by Django 2.2 on 2019-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0006_ma001fund_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ma001fund_list',
            name='fund_type01',
        ),
        migrations.AddField(
            model_name='ma001fund_list',
            name='create_date',
            field=models.DateField(default='2010-10-30', verbose_name='설정일'),
        ),
    ]
