# Generated by Django 2.0.13 on 2019-04-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0007_auto_20190410_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='entry_method',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='paying_period',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='present_age',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='risk_premium',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='transfer_date',
        ),
        migrations.RemoveField(
            model_name='ma001fund_list',
            name='input_percent',
        ),
        migrations.RemoveField(
            model_name='ma001fund_list',
            name='stock_percent',
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='insu_name02',
            field=models.TextField(default='변액연금보험 동행', max_length=100, verbose_name='보험명'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='sell_end',
            field=models.DateField(default='2010-01-01', verbose_name='가입일'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='sell_start',
            field=models.DateField(default='2010-01-01', verbose_name='가입일'),
        ),
        migrations.AddField(
            model_name='ma001fund_list',
            name='fund_name02',
            field=models.CharField(default='주식형', max_length=30, verbose_name='펀드명'),
        ),
        migrations.AddField(
            model_name='ma001fund_list',
            name='fund_type01',
            field=models.CharField(default='국내투자', max_length=30, verbose_name='펀드유형'),
        ),
        migrations.AddField(
            model_name='ma001fund_list',
            name='manage_company',
            field=models.CharField(default='주식형', max_length=30, verbose_name='펀드유형'),
        ),
    ]
