# Generated by Django 2.0.13 on 2019-04-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0008_auto_20190420_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma001fund_list',
            name='insu_name',
            field=models.CharField(max_length=30, null=True, verbose_name='보험명'),
        ),
    ]
