# Generated by Django 2.0.13 on 2019-04-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0010_auto_20190420_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma001fund_list',
            name='input_percent',
            field=models.IntegerField(default=10, verbose_name='편입비율'),
        ),
        migrations.AddField(
            model_name='ma001fund_list',
            name='stock_percent',
            field=models.IntegerField(default=10, verbose_name='주식비중'),
        ),
    ]
