# Generated by Django 2.0.13 on 2019-04-22 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vund', '0011_auto_20190422_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ma000insu_list',
            old_name='sell_end',
            new_name='entry_date',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='insu_name02',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='sell_start',
        ),
        migrations.RemoveField(
            model_name='ma001fund_list',
            name='fund_name02',
        ),
        migrations.RemoveField(
            model_name='ma001fund_list',
            name='fund_type01',
        ),
        migrations.RemoveField(
            model_name='ma001fund_list',
            name='insu_name',
        ),
        migrations.RemoveField(
            model_name='ma001fund_list',
            name='manage_company',
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='entry_method',
            field=models.CharField(default='적립', max_length=30, verbose_name='납입방법'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='gender',
            field=models.CharField(default='남자', max_length=5, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='업데이트일자'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='paying_period',
            field=models.IntegerField(default=10, verbose_name='납입기간'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='premium',
            field=models.IntegerField(default=1000000, verbose_name='월보험료'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='present_age',
            field=models.IntegerField(default=45, verbose_name='현재연령'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='risk_premium',
            field=models.IntegerField(default=1000, verbose_name='위험보험료'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='transfer_date',
            field=models.IntegerField(default=10, verbose_name='이체일'),
        ),
        migrations.AlterField(
            model_name='ma001fund_list',
            name='input_percent',
            field=models.IntegerField(default=10, verbose_name='투입비율'),
        ),
    ]
