# Generated by Django 2.0.13 on 2019-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0012_auto_20190422_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='entry_method',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='paying_period',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='present_age',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='risk_premium',
        ),
        migrations.RemoveField(
            model_name='ma000insu_list',
            name='transfer_date',
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='insu_name02',
            field=models.TextField(default='변액연금보험 동행', max_length=100, verbose_name='보험명'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='sell_end',
            field=models.DateField(default='2010-01-01', verbose_name='가입일'),
        ),
        migrations.AddField(
            model_name='ma000insu_list',
            name='sell_start',
            field=models.DateField(default='2010-01-01', verbose_name='가입일'),
        ),
    ]
