# Generated by Django 2.0.13 on 2019-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vund', '0014_remove_ma001fund_list_stock_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ma001fund_list',
            name='stock_percent',
            field=models.IntegerField(default=10, verbose_name='주식비중'),
        ),
    ]
