# Generated by Django 2.2 on 2019-04-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fa100Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(default='디스커버리', max_length=30, verbose_name='펀드명')),
                ('company', models.CharField(default='미래에셋', max_length=30, verbose_name='운용사')),
                ('fund_type', models.CharField(default='주식형', max_length=30, verbose_name='펀드유형')),
                ('area_section', models.CharField(default='국내', max_length=30, verbose_name='펀드구분')),
                ('fund_name_list', models.CharField(default='디스커버리', max_length=30, verbose_name='펀드명')),
                ('company_list', models.CharField(default='미래에셋', max_length=30, verbose_name='운용사')),
                ('fund_type_list', models.CharField(default='주식형', max_length=30, verbose_name='펀드유형')),
                ('area_section_list', models.CharField(default='국내', max_length=30, verbose_name='펀드구분')),
                ('create_date', models.DateField(default='2010-10-02', verbose_name='설정일')),
            ],
            options={
                'db_table': 'Funds_Fa100Out',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fa100In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(default='디스커버리', max_length=30, verbose_name='펀드명')),
                ('company', models.CharField(default='미래에셋', max_length=30, verbose_name='운용사')),
                ('fund_type', models.CharField(default='주식형', max_length=30, verbose_name='펀드유형')),
                ('area_section', models.CharField(default='국내', max_length=30, verbose_name='펀드구분')),
            ],
        ),
        migrations.CreateModel(
            name='Ma000fund_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.TextField(default='디스커버리', max_length=100, verbose_name='펀드명')),
                ('fund_code', models.CharField(default='1234', max_length=30, verbose_name='펀드코드')),
                ('company', models.CharField(default='미래에셋', max_length=30, verbose_name='운용사')),
                ('fund_type', models.CharField(default='주식형', max_length=30, verbose_name='펀드유형')),
                ('create_date', models.DateField(default='2010-10-02', verbose_name='설정일')),
                ('area_section', models.CharField(default='국내', max_length=30, verbose_name='펀드구분')),
                ('fund_money_million', models.IntegerField(default=0, verbose_name='설정액 백만원')),
                ('fund_money_hunmillion', models.IntegerField(default=0, verbose_name='설정액 억')),
                ('manage_pay', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='운용보수')),
                ('sell_pay', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='판매보수')),
                ('bank_pay', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='수탁보수')),
                ('office_pay', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='사무관리보수')),
                ('total_pay', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='총보수')),
                ('averige_pay', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='보수평균')),
                ('before_charge', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='선취수수료')),
                ('after_charge', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='후취수수료')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='업데이트일자')),
                ('entry_date', models.DateField(default='2010-10-02', verbose_name='가입일')),
                ('transfer_date', models.IntegerField(default=10, verbose_name='이체일')),
                ('entry_money', models.IntegerField(default=1000000, verbose_name='가입금액')),
                ('entry_method', models.CharField(default='적립', max_length=30, verbose_name='납입방법')),
            ],
        ),
    ]
