# Generated by Django 2.0.13 on 2019-04-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_order_orderitem_ordertransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderTransaction',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
