# Generated by Django 2.0.13 on 2019-04-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20190429_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
