# Generated by Django 2.0.13 on 2019-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20190429_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='input_percent',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
