# Generated by Django 2.0.13 on 2019-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20190429_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='input_percent',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, null=True),
        ),
    ]
