# Generated by Django 2.0.13 on 2019-05-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20190506_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='insu_name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
