# Generated by Django 2.0.13 on 2019-05-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_insu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, default=1, max_digits=10, null=True)),
            ],
        ),
    ]
