# Generated by Django 2.0.13 on 2019-05-07 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_product02'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product02',
            new_name='Product12',
        ),
    ]
