# Generated by Django 2.0.13 on 2019-05-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20190507_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, default=1, max_digits=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product12',
        ),
    ]
