# Generated by Django 2.0.13 on 2019-06-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20190507_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_percent',
        ),
        migrations.RemoveField(
            model_name='product05',
            name='price',
        ),
        migrations.AddField(
            model_name='product05',
            name='price01',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
