# Generated by Django 2.0.13 on 2019-06-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_stock_percent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product05',
        ),
    ]
