# Generated by Django 2.0.13 on 2019-10-25 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ae00Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(default='종합주가', max_length=7, verbose_name='구분')),
                ('start_date', models.DateField(default='2005-01-05', verbose_name='시작일')),
                ('end_date', models.DateField(default='2019-08-20', verbose_name='종료일')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ae05Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(default='종합주가지수', max_length=10, verbose_name='구분')),
                ('start_date', models.DateField(default='2005-01-05', verbose_name='시작일')),
                ('end_date', models.DateField(default='2019-01-05', verbose_name='종료일')),
                ('accum_premium', models.IntegerField(default=100000000, verbose_name='적립총보험료')),
                ('defer_premium', models.IntegerField(default=100000000, verbose_name='거치보험료')),
                ('stock_start_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='주식 시작 기준가')),
                ('bond_start_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='채권 시작 기준가')),
                ('stock_end_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='주식 종료 기준가')),
                ('bond_end_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='채권 종료 기준가')),
                ('accum_stock', models.IntegerField(default=100000000, verbose_name='적립그냥주식평가금액')),
                ('accum_stock_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='적립그냥주식수익률')),
                ('accum_change', models.IntegerField(default=100000000, verbose_name='적립펀번주식평가금액')),
                ('accum_change_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='적립펀번주식수익률')),
                ('defer_stock', models.IntegerField(default=100000000, verbose_name='거치그냥주식평가금액')),
                ('defer_stock_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='거치그냥주식수익률')),
                ('defer_change', models.IntegerField(default=100000000, verbose_name='거치펀번평가금액')),
                ('defer_change_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='거치펀번수익률')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
