# Generated by Django 2.0.13 on 2019-11-07 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ae10Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(default='종합주가', max_length=10, verbose_name='구분')),
                ('date', models.DateField(default='2005-01-05', verbose_name='시작일')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='주식 기준가')),
                ('bond', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='채권 기준가')),
                ('stock_change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='주식변경그래프')),
                ('bond_change', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='채권변경그래프')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
