# Generated by Django 2.0.13 on 2019-11-07 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders03', '0002_ae10graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ae11Startend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2005-01-05', verbose_name='날자')),
                ('start', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='시작일 그래프')),
                ('end', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='끝 그래프')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='ae10graph',
            name='date',
            field=models.DateField(default='2005-01-05', verbose_name='날자'),
        ),
    ]
