# Generated by Django 2.0.13 on 2019-11-08 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders03', '0004_ae01out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ae01out',
            old_name='owner',
            new_name='user',
        ),
    ]
