# Generated by Django 2.0.13 on 2019-11-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders03', '0005_auto_20191108_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='ae05result',
            name='accum_rate_gap',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='적립수익률차이'),
        ),
        migrations.AddField(
            model_name='ae05result',
            name='dafer_rate_gap',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='거치수익률차이'),
        ),
        migrations.AddField(
            model_name='ae05result',
            name='stock_rate',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='주식상승률'),
        ),
    ]
