# Generated by Django 2.0.13 on 2019-11-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders03', '0006_auto_20191109_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ae05result',
            old_name='dafer_rate_gap',
            new_name='defer_rate_gap',
        ),
    ]
