# Generated by Django 2.0.13 on 2019-11-21 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders03', '0007_auto_20191109_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ae13Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='주식변경개수')),
                ('bond_count', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='채권변경개수')),
                ('total_count', models.DecimalField(decimal_places=0, max_digits=5, verbose_name='총변경개수')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ae10graph',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='ae00input',
            name='start_date',
            field=models.DateField(default='1996-01-05', verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='ae01out',
            name='start_date',
            field=models.DateField(default='1996-01-05', verbose_name='시작일'),
        ),
    ]
