# Generated by Django 2.0.13 on 2019-11-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders03', '0008_auto_20191121_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ae13count',
            old_name='owner',
            new_name='user',
        ),
    ]
