# Generated by Django 2.0.13 on 2019-11-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders03', '0010_af01input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Af07Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(default='종합주가지수', max_length=10, verbose_name='구분')),
                ('accum_premium', models.IntegerField(default=100000000, verbose_name='적립총보험료')),
                ('defer_premium', models.IntegerField(default=100000000, verbose_name='거치보험료')),
                ('accum_stock', models.IntegerField(default=100000000, verbose_name='적립그냥주식평가금액')),
                ('accum_stock_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='적립그냥주식수익률')),
                ('accum_change', models.IntegerField(default=100000000, verbose_name='적립펀번주식평가금액')),
                ('accum_change_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='적립펀번주식수익률')),
                ('accum_rate_gap', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='적립수익률차이')),
                ('defer_stock', models.IntegerField(default=100000000, verbose_name='거치그냥주식평가금액')),
                ('defer_stock_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='거치그냥주식수익률')),
                ('defer_change', models.IntegerField(default=100000000, verbose_name='거치펀번평가금액')),
                ('defer_change_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='거치펀번수익률')),
                ('defer_rate_gap', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='거치수익률차이')),
            ],
        ),
    ]
