# Generated by Django 2.0.13 on 2019-11-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders03', '0011_af07result'),
    ]

    operations = [
        migrations.AddField(
            model_name='af07result',
            name='total_count',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True, verbose_name='총검증개수'),
        ),
    ]
