# Generated by Django 2.0.13 on 2019-11-27 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders03', '0012_af07result_total_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Af14Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2005-01-05', verbose_name='날자')),
                ('kospi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='종합주가 그래프')),
                ('revers_kospi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='역종합 그래프')),
                ('start', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='투자시작 그래프')),
                ('end', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='투자끝 그래프')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
