# Generated by Django 2.0.13 on 2019-11-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders03', '0013_af14graph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='af14graph',
            old_name='revers_kospi',
            new_name='reverse_kospi',
        ),
    ]
