# Generated by Django 2.0.13 on 2019-11-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders03', '0014_auto_20191127_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='af14graph',
            name='user',
        ),
    ]
