# Generated by Django 2.0.13 on 2019-11-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders03', '0015_remove_af14graph_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='af14graph',
            name='zero',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='0그래프'),
        ),
    ]
