# Generated by Django 2.0.13 on 2020-01-04 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders03', '0017_auto_20191202_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ae05Result01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_start_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='주식 시작 기준가')),
                ('stock_end_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='주식 종료 기준가')),
                ('stock_rate', models.DecimalField(decimal_places=1, max_digits=5, null=True, verbose_name='주식상승률')),
                ('bond_start_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='채권 시작 기준가')),
                ('bond_end_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='채권 종료 기준가')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='accum_change',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='accum_change_rate',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='accum_rate_gap',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='accum_stock',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='accum_stock_rate',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='bond_end_price',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='bond_start_price',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='defer_change',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='defer_change_rate',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='defer_rate_gap',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='defer_stock',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='defer_stock_rate',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='stock_end_price',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='stock_rate',
        ),
        migrations.RemoveField(
            model_name='ae05result',
            name='stock_start_price',
        ),
        migrations.AddField(
            model_name='ae05result',
            name='accum_bond_count',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='적립채권좌수'),
        ),
        migrations.AddField(
            model_name='ae05result',
            name='accum_count',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='그냥주식좌수'),
        ),
        migrations.AddField(
            model_name='ae05result',
            name='accum_stock_count',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='적립주식좌수'),
        ),
        migrations.AddField(
            model_name='ae05result',
            name='defer_bond_count',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='거치채권좌수'),
        ),
        migrations.AddField(
            model_name='ae05result',
            name='defer_count',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='그냥채권좌수'),
        ),
        migrations.AddField(
            model_name='ae05result',
            name='defer_stock_count',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='거치주식좌수'),
        ),
    ]
