# Generated by Django 2.0.13 on 2019-07-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad03Returnmoneyout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_month', models.IntegerField(default=100, verbose_name='경과월')),
                ('age', models.IntegerField(default=45, verbose_name='연령')),
                ('path_year', models.IntegerField(default=10, verbose_name='경과년')),
                ('total_premium', models.IntegerField(default=100000000, verbose_name='총납입현황')),
                ('payment', models.IntegerField(default=130000000, verbose_name='계약자적립금')),
                ('return_money', models.IntegerField(default=130000000, verbose_name='해지환급금')),
                ('year', models.CharField(default='1년', max_length=25, verbose_name='경과년월')),
                ('return_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='환급률')),
                ('expect_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='예상수익률')),
            ],
            options={
                'db_table': 'Orders02_Ad03Returnmoneyout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ad04Pentionmoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_premium', models.IntegerField(default=100000000, verbose_name='총납입현황')),
                ('pention_money', models.IntegerField(default=130000000, verbose_name='연금재원')),
            ],
            options={
                'db_table': 'Orders02_Ad04Pentionmoney',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ad05Pentionout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whole_10', models.IntegerField(default=130000000, verbose_name='상속연금10년보증')),
                ('whole_20', models.IntegerField(default=130000000, verbose_name='상속연금20년보증')),
                ('whole_80', models.IntegerField(default=130000000, verbose_name='상속연금80세보증')),
                ('set_10', models.IntegerField(default=130000000, verbose_name='10년확정')),
                ('set_15', models.IntegerField(default=130000000, verbose_name='15년확정')),
                ('set_20', models.IntegerField(default=130000000, verbose_name='20년확정')),
                ('inherit_month', models.IntegerField(default=130000000, verbose_name='상속연금')),
                ('inherit_lumpsum', models.IntegerField(default=130000000, verbose_name='상속일시금')),
                ('total_whole_10', models.IntegerField(default=130000000, verbose_name='총상속연금10년보증')),
                ('total_whole_20', models.IntegerField(default=130000000, verbose_name='총상속연금20년보증')),
                ('total_whole_80', models.IntegerField(default=130000000, verbose_name='총상속연금80세보증')),
                ('total_set_10', models.IntegerField(default=130000000, verbose_name='총10년확정')),
                ('total_set_15', models.IntegerField(default=130000000, verbose_name='총15년확정')),
                ('total_set_20', models.IntegerField(default=130000000, verbose_name='총20년확정')),
                ('total_inherit_month', models.IntegerField(default=130000000, verbose_name='총상속연금')),
                ('total_premium', models.IntegerField(default=130000000, verbose_name='총납입보험료')),
                ('pention_money', models.IntegerField(default=130000000, verbose_name='연금개시재원')),
                ('return_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='환급률')),
            ],
            options={
                'db_table': 'Orders02_Ad05Pentionout',
                'managed': False,
            },
        ),
    ]
