# Generated by Django 2.0.13 on 2019-10-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders02', '0002_ad03returnmoneyout_ad04pentionmoney_ad05pentionout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad06Enterout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_premium', models.IntegerField(default=100000000, verbose_name='총납입현황')),
                ('payment', models.IntegerField(default=130000000, verbose_name='계약자적립금')),
                ('return_rate', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='수익률')),
                ('count', models.IntegerField(default=100, verbose_name='경과월수')),
            ],
            options={
                'db_table': 'Orders02_Ad06Enterout',
                'managed': False,
            },
        ),
    ]
