# Generated by Django 2.0.13 on 2020-01-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
