# Generated by Django 2.0.13 on 2019-10-25 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aa00Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default='2000-01-10', verbose_name='시작일')),
                ('end_date', models.DateField(default='2019-08-10', verbose_name='종료일')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aa01Pathmonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_month', models.IntegerField(default=100, verbose_name='경과월')),
                ('start_date', models.DateField(default='2000-01-10', verbose_name='시작일')),
                ('end_date', models.DateField(default='2019-08-10', verbose_name='종료일')),
            ],
        ),
    ]
