# Generated by Django 2.0.13 on 2020-01-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200106_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund10entry',
            name='fund_made_date',
            field=models.DateField(null=True),
        ),
    ]
