# Generated by Django 2.0.13 on 2020-01-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_fund10entry_fund_made_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund10entry',
            name='fund_made_date',
        ),
        migrations.AddField(
            model_name='fund10entry',
            name='warning',
            field=models.CharField(max_length=50, null=True, verbose_name='경고'),
        ),
    ]
