# Generated by Django 2.0.13 on 2019-10-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HungbuOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kospi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='종합주가지수')),
            ],
            options={
                'db_table': 'orders06_HungbuOut',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HungbuOut02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kospi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='종합주가지수')),
                ('hungbu_entry_date', models.DateField()),
                ('nolbu_entry_date', models.DateField()),
                ('hungbu_pention_start_date', models.DateField()),
                ('nolbu_pention_start_date', models.DateField()),
            ],
        ),
    ]
